Rewrite host
ROCMondriaanTIN/if-sd-php-healthone-sportcentem pull request #1
Opened 2021-09-01 13:03 UTC by rcspringer

Please check the code

2021-09-01 13:20 UTC, gijsdl requested changes

2021-09-01 13:20 UTC, gijsdl commented on Modules/Products.php
> +    global $pdo, $params;
Remove unused variable

2021-09-01 13:20 UTC, gijsdl commented on Templates/categories.php
> +<body style="background-color: gainsboro">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/categories.php
> +<div class="container" style="background-color: white">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/categories.php
> +                            <img class="img-responsive center-block" style="width:70%"
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/defaults/footer.php
> +    <img class="pull-right img-thumbnail " width="40"  style="margin-top: -10px;margin-bottom: 10px" src="/img/pinterest.png" />
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/defaults/header.php
> +    <div class="row" style="margin-top: 20px">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/defaults/pictures.php
> +    <img style="margin-bottom: 20px" class="img-responsive" src='/img/healthone-wide.png' />
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/home.php
> +        <div class="container" style="background-color: white">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/product.php
>  <body style="background-color: gainsboro">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/product.php
>  <div class="container" style="background-color: white">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/product.php
> +                <img class="img-responsive center-block" style="width:70%" src='/img/<?= $product->picture ?>'/>
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/products.php
>  <body style="background-color: gainsboro">
Style inline to CSS

2021-09-01 13:20 UTC, gijsdl commented on Templates/products.php
> +                            <img class="img-responsive center-block" style="width:70%" src='/img/<?= $product->picture ?>' />
Style inline to CSS

2021-09-01 13:27 UTC, rcspringer commented on Modules/Products.php
> +    global $pdo, $params;
Should be fixed

2021-09-01 13:27 UTC, rcspringer commented on Templates/categories.php
> +<body style="background-color: gainsboro">
Fixed

2021-09-01 13:27 UTC, rcspringer commented on Templates/categories.php
> +<div class="container" style="background-color: white">
Fixed

2021-09-01 13:28 UTC, rcspringer commented on Templates/categories.php
> +                            <img class="img-responsive center-block" style="width:70%"
Fixed

2021-09-01 13:28 UTC, rcspringer commented on Templates/defaults/footer.php
> +    <img class="pull-right img-thumbnail " width="40"  style="margin-top: -10px;margin-bottom: 10px" src="/img/pinterest.png" />
Fixed

2021-09-01 13:28 UTC, rcspringer commented on Templates/product.php
>  <body style="background-color: gainsboro">
Fixed

2021-09-01 13:28 UTC, rcspringer commented on Templates/products.php
> +                            <img class="img-responsive center-block" style="width:70%" src='/img/<?= $product->picture ?>' />
Fixed

2021-09-01 13:28 UTC, gijsdl approved these changes

2021-09-03 14:07 UTC, mjlinden approved these changes
<base href="http://healthone/" target="_blank">
Wanneer de url -> healthone/products/1
dan worden resources gezocht in healthone/products/img etc
deze regel in de header zorgt ervoor dat resources nu gezocht worden in
healthone/img/ etc

2021-09-06 11:20 UTC, merged